## Mini-Project 1

In [1]:
import pandas as pd

df = pd.read_csv("CSE_student_performances.csv")
df.head()

,Age,Gender,AcademicPerformance,TakingNoteInClass,DepressionStatus,FaceChallangesToCompleteAcademicTask,LikePresentation,SleepPerDayHours,NumberOfFriend,LikeNewThings
0,23,Male,Average,No,Sometimes,Yes,Yes,12,NaN,Yes
1,23,Male,Excellent,Sometimes,Yes,No,Yes,8,80.0,Yes
2,24,Male,Average,No,Sometimes,Sometimes,No,8,10.0,Yes
3,20,Female,Good,Yes,Sometimes,Yes,No,5,15.0,Yes
4,24,Female,Average,Yes,Yes,Yes,Yes,5,2.0,Yes

In [3]:
df.shape

(99, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Age                                   99 non-null     int64
 1   Gender                                99 non-null     object
 2   AcademicPerformance                   95 non-null     object
 3   TakingNoteInClass                     99 non-null     object
 4   DepressionStatus                      92 non-null     object
 5   FaceChallangesToCompleteAcademicTask  99 non-null     object
 6   LikePresentation                      99 non-null     object
 7   SleepPerDayHours                      99 non-null     int64
 8   NumberOfFriend                        95 non-null     float64
 9   LikeNewThings                         99 non-null     object
dtypes: float64(1), int64(2), object(7)
memory usage: 7.9+ KB

In [7]:
df.describe()

            Age   SleepPerDayHours  NumberOfFriend
count  99.000000         99.000000       95.000000
mean   22.515152          6.717172       16.189474
std     1.560767          1.738169       25.397811
min    20.000000          4.000000        0.000000
25%    21.000000          5.000000        3.000000
50%    23.000000          7.000000        6.000000
75%    24.000000          8.000000       15.000000
max    25.000000         12.000000      100.000000

In [9]:
df.drop('LikePresentation', axis = 1, inplace = True)
df

,Age,Gender,AcademicPerformance,TakingNoteInClass,DepressionStatus,FaceChallangesToCompleteAcademicTask,SleepPerDayHours,NumberOfFriend,LikeNewThings
0,23,Male,Average,No,Sometimes,Yes,12,NaN,Yes
1,23,Male,Excellent,Sometimes,Yes,No,8,80.0,Yes
2,24,Male,Average,No,Sometimes,Sometimes,8,10.0,Yes
3,20,Female,Good,Yes,Sometimes,Yes,5,15.0,Yes
4,24,Female,Average,Yes,Yes,Yes,5,2.0,Yes
...,...,...,...,...,...,...,...,...,...
94,21,Male,Good,Yes,Sometimes,Yes,6,4.0,Yes
95,21,Female,Good,Yes,Yes,No,6,6.0,Yes
96,25,Male,Good,Yes,Sometimes,No,4,9.0,No
97,21,Male,Good,Yes,No,Sometimes,10,23.0,Yes
98,22,Female,Average,Yes,No,No,7,3.0,Yes

In [11]:
import re

cols = list(df.columns)

for i in range(len(cols)):
    cols[i] = " ".join(re.split('(?<=.)(?=[A-Z])', cols[i]))

df.columns = cols
df

,Age,Gender,Academic Performance,Taking Note In Class,Depression Status,Face Challanges To Complete Academic Task,Sleep Per Day Hours,Number Of Friend,Like New Things
0,23,Male,Average,No,Sometimes,Yes,12,NaN,Yes
1,23,Male,Excellent,Sometimes,Yes,No,8,80.0,Yes
2,24,Male,Average,No,Sometimes,Sometimes,8,10.0,Yes
3,20,Female,Good,Yes,Sometimes,Yes,5,15.0,Yes
4,24,Female,Average,Yes,Yes,Yes,5,2.0,Yes
...,...,...,...,...,...,...,...,...,...
94,21,Male,Good,Yes,Sometimes,Yes,6,4.0,Yes
95,21,Female,Good,Yes,Yes,No,6,6.0,Yes
96,25,Male,Good,Yes,Sometimes,No,4,9.0,No
97,21,Male,Good,Yes,No,Sometimes,10,23.0,Yes
98,22,Female,Average,Yes,No,No,7,3.0,Yes

In [13]:
df.drop_duplicates(inplace = True)
df.dropna(inplace = True)
df.shape

(30, 9)

In [15]:
df["Sleep Per Day Hours"].mean()

6.733333333333333

In [25]:
df[df["Academic Performance"] == "Excellent"]["Sleep Per Day Hours"].mean()

7.666666666666667

In [27]:
df[df["Depression Status"] == "Yes"]["Sleep Per Day Hours"].mean()

5.8